write:
  # -- Number of replicas for the write
  replicas: 2
  nodeSelector:
    Addons-Services: "true"
  resources: {}
  persistence:
    size: 10Gi

read:
  # -- Number of replicas for the read
  replicas: 2
  nodeSelector:
    Addons-Services: "true"
  resources: {}
  persistence:
    size: 10Gi

backend:
  # -- Number of replicas for the backend
  replicas: 2
  nodeSelector:
    Addons-Services: "true"
  resources: {}
  persistence:
    size: 10Gi

gateway:
  replicas: 2
  resources: {}

chunksCache:
  resources:
    limits:
      cpu: 1500m
      memory: 3500Mi
    requests:
      cpu: 500m
      memory: 1024Mi
  nodeSelector:
    Addons-Services: "true"
