loki:
  enabled: true
  isDefault: false
  config:
    table_manager:
      retention_deletes_enabled: true
      retention_period: 48h
    chunk_store_config:
      max_look_back_period: 24h
    compactor:
      compaction_interval: 5m
      retention_enabled: true
      retention_delete_delay: 2m
      retention_delete_worker_count: 10000
    limits_config:
      retention_period: 168h
      enforce_metric_name: false
      max_entries_limit_per_query: 5000
      reject_old_samples: true
      reject_old_samples_max_age: 168h
  resources:
    limits:
      cpu: 1000m
      memory: 1536Mi
    requests:
      cpu: 100m
      memory: 300Mi
  persistence:
    enabled: true
    storageClassName: ${storage_class_name}
    size: "20Gi"
  ingress:
    enabled: ${enable_loki_internal_ingress}
    annotations:
    kubernetes.io/ingress.class: "internal-nginx"
    kubernetes.io/tls-acme: "false"
    hosts:
    - host: ${loki_hostname}
      paths:
      - /
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: "Addons-Services"
            operator: In
            values:
            - "true"

promtail:
  enabled: true
  config:
    lokiAddress: http://{{ .Release.Name }}:3100/loki/api/v1/push

fluent-bit:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false
  isDefault: false


outputs:
  main: |-
    output {
      loki {
        url => "http://loki:3100/loki/api/v1/push"
        #username => "test"
        #password => "test"
      }
      # stdout { codec => rubydebug }
    }
